grafana:
  image: grafana/grafana:9.1.8
  ports:
    - "3000:3000"
  volumes:
    - ./dist:/var/lib/grafana/plugins/dalvany-image-panel
  environment:
    - TERM=linux
    - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=dalvany-image-panel
    - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
